/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ClientMessage =
  Hello | Configure | Kick | Start | Leave | ConfirmCard | NightAction | ReadyToVote | Vote | Rematch;
export type RoleId =
  | "werewolf"
  | "minion"
  | "mason"
  | "seer"
  | "robber"
  | "troublemaker"
  | "drunk"
  | "insomniac"
  | "hunter"
  | "tanner"
  | "villager";
export type ServerMessage = StateMessage | ErrorMessage;
export type Phase = "lobby" | "deal" | "night" | "day" | "vote" | "reveal";
export type Team = "village" | "werewolf" | "tanner";
export type ErrorCode =
  | "not_member"
  | "not_host"
  | "not_playing"
  | "wrong_phase"
  | "room_full"
  | "game_in_progress"
  | "player_count"
  | "players_offline"
  | "deck_size"
  | "too_many_copies"
  | "unknown_player"
  | "cannot_kick_self"
  | "not_your_turn"
  | "already_acted"
  | "bad_targets"
  | "already_voted";
/**
 * 游戏规则以外的错误。
 */
export type ProtocolErrorCode = "bad_message" | "bad_token" | "room_not_found" | "removed" | "internal";

/**
 * WebSocket 连上之后的第一帧：还不是成员就加入，已经是成员就恢复。
 */
export interface Hello {
  type: "hello";
  token: string;
  name: string;
}
export interface Configure {
  type: "configure";
  settings: Settings;
}
export interface Settings {
  deck: RoleId[] | null;
  timings: Timings;
}
/**
 * 各阶段时长，单位秒。
 */
export interface Timings {
  deal: number;
  night_step: number;
  day: number;
  vote: number;
}
export interface Kick {
  type: "kick";
  player: string;
}
export interface Start {
  type: "start";
}
export interface Leave {
  type: "leave";
}
export interface ConfirmCard {
  type: "confirm_card";
}
export interface NightAction {
  type: "night_action";
  targets: string[];
}
export interface ReadyToVote {
  type: "ready_to_vote";
}
export interface Vote {
  type: "vote";
  target: string;
}
export interface Rematch {
  type: "rematch";
}
export interface StateMessage {
  type: "state";
  seq: number;
  server_now: number;
  view: PlayerView;
}
export interface PlayerView {
  phase: Phase;
  ends_at: number | null;
  room: RoomView;
  me: MeView;
  prompt: Prompt | null;
  deal: DealView | null;
  night: NightView | null;
  day: DayView | null;
  vote: VoteView | null;
  result: ResultView | null;
}
export interface RoomView {
  code: string;
  host: string;
  members: MemberView[];
  deck: RoleId[];
  auto_deck: boolean;
  timings: Timings;
}
export interface MemberView {
  id: string;
  name: string;
  online: boolean;
  seat: number | null;
}
export interface MeView {
  id: string;
  seat: number | null;
  card: RoleId | null;
  knowledge: (SawCard | SawPlayers | Swapped)[];
}
/**
 * 看到了某个位置上的牌。
 */
export interface SawCard {
  type: "saw_card";
  step: RoleId;
  slot: string;
  role: RoleId;
}
/**
 * 得知哪些玩家拿着某个角色，例如狼互认、爪牙看狼。players 可以为空。
 */
export interface SawPlayers {
  type: "saw_players";
  step: RoleId;
  role: RoleId;
  players: string[];
}
/**
 * 交换了两个位置上的牌。交换本身不代表看到了牌。
 */
export interface Swapped {
  type: "swapped";
  step: RoleId;
  /**
   * @minItems 2
   * @maxItems 2
   */
  slots: [string, string];
}
/**
 * 玩家此刻能做的选择：从 options 里挑一种。required 的选择超时后由系统随机代选。
 */
export interface Prompt {
  options: TargetOption[];
  required: boolean;
}
/**
 * 选 count 个目标。player 指其他玩家（不含自己），center 指底牌。
 */
export interface TargetOption {
  kind: "player" | "center";
  count: number;
}
export interface DealView {
  confirmed: string[];
}
export interface NightView {
  step: RoleId;
  index: number;
  total: number;
}
export interface DayView {
  ready: string[];
}
export interface VoteView {
  voted: string[];
  mine: string | null;
}
export interface ResultView {
  dealt: {
    [k: string]: RoleId;
  };
  final: {
    [k: string]: RoleId;
  };
  knowledge: {
    [k: string]: (SawCard | SawPlayers | Swapped)[];
  };
  night_log: NightLogEntry[];
  votes: {
    [k: string]: string;
  };
  deaths: string[];
  winning_teams: Team[];
  winners: string[];
}
export interface NightLogEntry {
  step: RoleId;
  player: string;
  targets: string[];
  auto: boolean;
}
export interface ErrorMessage {
  type: "error";
  code: ErrorCode | ProtocolErrorCode;
  ref: string | null;
}
